# Generated by Django 5.1.1 on 2024-11-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
