# Generated by Django 5.1.1 on 2024-11-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.PositiveIntegerField(default=987654321),
        ),
    ]
