# Generated by Django 5.1.1 on 2024-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.PositiveIntegerField(default=992),
        ),
    ]
