# Generated by Django 5.1.1 on 2024-11-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='updated_at',
        ),
    ]
