# Generated by Django 5.1.1 on 2024-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_receiver_friendrequest_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='sent', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
