# Generated by Django 5.1.1 on 2024-11-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_receiver_friendrequest_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
