# Generated by Django 5.1.1 on 2024-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_friendrequest_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='receiver',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
