# Generated by Django 5.1.1 on 2024-11-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_sender_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
