# Generated by Django 5.1.1 on 2024-11-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
