# Generated by Django 5.1.1 on 2024-11-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
