# Generated by Django 5.1.1 on 2024-11-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
