# Generated by Django 5.1.1 on 2024-11-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('O', 'open'), ('C', 'Close')], default='O', max_length=1),
        ),
    ]
