# Generated by Django 5.1.1 on 2024-11-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='accounts_type',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('F', 'Friend')], default='O', max_length=1),
        ),
    ]
