# Generated by Django 5.1.1 on 2024-11-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_customuser_type_customuser_accounts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accounts_type',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close - request'), ('F', 'Friend - friend reuest')], default='O', max_length=1),
        ),
    ]
