# Generated by Django 5.1.1 on 2024-11-16 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_customuser_accounts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accounts_type',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close - request'), ('F', 'Friend - friend request')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='LanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tg', 'Tajik')], default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
