# Generated by Django 5.1.1 on 2024-11-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_customuser_accounts_type_languagepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.languagepreference'),
        ),
        migrations.AlterField(
            model_name='languagepreference',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
