# Generated by Django 5.1.1 on 2024-11-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_customuser_language_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language_preference',
        ),
        migrations.DeleteModel(
            name='LanguagePreference',
        ),
    ]
