# Generated by Django 5.1.1 on 2024-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('greate', 'Grate 😎'), ('good', 'Good 😍'), ('normal', 'Normal 😐'), ('sad', 'Sad 😔'), ('bad', 'Bad 😡'), ('super_bad', 'Super Bad 🤬')], default='normal', max_length=10),
        ),
    ]
