# Generated by Django 5.1.1 on 2024-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('greate', 'Greate 😎'), ('good', 'Good 😍'), ('normal', 'Normal 😐'), ('sad', 'Sad 😔'), ('bad', 'Bad 😡'), ('super_bad', 'Super Bad 🤬')], default='normal', max_length=10),
        ),
    ]
