# Generated by Django 5.1.1 on 2024-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accounts_type',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close - request'), ('F', 'Friend - request')], default='O', max_length=1),
        ),
    ]
