# Generated by Django 5.1.1 on 2024-11-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_blockeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
