# Generated by Django 5.1.1 on 2024-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_delete_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('news', 'News'), ('sports', 'Sports')], max_length=50, null=True),
        ),
    ]
