# Generated by Django 5.1.1 on 2024-11-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_usertheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTheme',
        ),
    ]
