# Generated by Django 5.1.1 on 2024-11-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
