# Generated by Django 5.1.1 on 2024-12-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_tv_shows',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job',
        ),
    ]
