# Generated by Django 5.1.1 on 2024-12-06 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_customuser_cover_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, max_length=500, null=True)),
                ('music', models.FileField(blank=True, null=True, upload_to='flashtops/music/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashtops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashTopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flashtops/images/')),
                ('flashtop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.flashtop')),
            ],
        ),
    ]
