# Generated by Django 5.1.1 on 2024-12-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_flashtop_flashtopimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashtop',
            name='caption',
        ),
        migrations.AddField(
            model_name='flashtop',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='flash_images/'),
        ),
        migrations.AlterField(
            model_name='flashtop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flashtop',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='flash_music/'),
        ),
        migrations.AlterField(
            model_name='flashtop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FlashTopImage',
        ),
    ]
