# Generated by Django 5.1.1 on 2024-12-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_story_options_rename_media_story_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
