# Generated by Django 5.1.1 on 2024-12-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_blockeduser_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
