# Generated by Django 5.1.1 on 2024-12-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_commentshorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likephoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_photo', to='users.photo'),
        ),
    ]
