# Generated by Django 5.1.1 on 2024-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_likephoto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
