# Generated by Django 5.1.1 on 2024-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_stories_likestories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/stories/'),
        ),
    ]
