# Generated by Django 5.1.1 on 2024-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_usermusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_type',
            field=models.CharField(choices=[('C', 'Company'), ('P', 'Default - profile'), ('S', 'Online store')], default='P', max_length=1),
        ),
    ]
