# Generated by Django 5.1.1 on 2024-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_flyer_commentflyer_likeflyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('clothes', 'Clothes'), ('items', 'Items'), ('devices', 'Devices'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
