# Generated by Django 5.1.1 on 2024-12-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_alter_flyer_video_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
