# Generated by Django 5.1.1 on 2024-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_pic',
            field=models.ImageField(blank=True, null=True, upload_to='groups_pics/'),
        ),
    ]
