# Generated by Django 5.1.1 on 2024-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_group_group_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_pic',
            field=models.ImageField(blank=True, null=True, upload_to='group_pics/'),
        ),
    ]
