# Generated by Django 5.1.1 on 2024-12-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_friendrequest_notification_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
