# Generated by Django 5.1.1 on 2024-12-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_remove_friendrequest_notification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
