# Generated by Django 5.1.1 on 2025-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_videocall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocall',
            old_name='call_end_time',
            new_name='call_ended_at',
        ),
        migrations.RenameField(
            model_name='videocall',
            old_name='call_start_time',
            new_name='call_started_at',
        ),
        migrations.AlterField(
            model_name='videocall',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('accepted', 'Accepted'), ('ended', 'Ended')], default='initiated', max_length=10),
        ),
    ]
