# Generated by Django 5.1.1 on 2025-01-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_rename_call_end_time_videocall_call_ended_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
