# Generated by Django 5.1.1 on 2025-01-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_videocall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
