# Generated by Django 5.1.1 on 2025-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_customuser_blocked_users_alter_call_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='qB7Pq7QVrTNO', max_length=100, unique=True),
        ),
    ]
