# Generated by Django 5.1.1 on 2025-01-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_alter_call_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='bIQFXDNhQTig', max_length=100, unique=True),
        ),
    ]
