# Generated by Django 5.1.1 on 2025-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_alter_call_room_name_group_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='h8KDUE01nHJt', max_length=100, unique=True),
        ),
    ]
