# Generated by Django 5.1.1 on 2025-01-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_shorts_low_res_video_alter_call_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorts',
            name='low_res_video',
        ),
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='cglvztykveAb', max_length=100, unique=True),
        ),
    ]
