# Generated by Django 5.1.1 on 2025-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_alter_call_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='hAeiIuf1sobV', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_pics'),
        ),
    ]
