# Generated by Django 5.1.1 on 2025-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_alter_call_room_name_alter_group_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='K3Rt4NzrDbcm', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='group_images/'),
        ),
    ]
