# Generated by Django 5.1.1 on 2025-01-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_alter_call_room_name_alter_group_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='2JxkgaqnIZtc', max_length=100, unique=True),
        ),
    ]
