# Generated by Django 5.1.1 on 2025-01-18 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_alter_call_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='Gu3yDqwexkXU', max_length=100, unique=True),
        ),
    ]
