# Generated by Django 5.1.1 on 2025-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_groupmessage_readers_alter_call_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='room_name',
            field=models.CharField(default='0rTUJKOpYF6P', max_length=100, unique=True),
        ),
    ]
